### PR TITLE
Elixir 1.19 Compatibility and Test Fixes

### PR DESCRIPTION
**Pull request by nyo16**
### Change description
 Move preferred_cli_env from project/0 to new cli/0 function using preferred_envs key
  - Bump absinthe to >= 1.8.0 (was >= 1.7.0)
  - Bump credo to ~> 1.7.14 (was ~> 1.7.7)
  - Increase Grafana Agent downloader test timeouts
### What problem does this solve?
 Fixes compatibility issues with Elixir 1.19:
  - preferred_cli_env in project/0 was deprecated in Elixir 1.15
  - absinthe 1.7.x fails to compile with Elixir 1.19
  - credo 1.7.7 has a regex compilation error with Elixir 1.19
  - Grafana Agent downloader tests were timing out due to large file downloads (~56MB per binary)
Issue number: (if applicable)
N/A
### Example usage
  N/A - internal fixes only
### Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have added documentation to cover my changes.
- [ ] My changes have passed unit tests and have been tested E2E in an example project.

### CODE REVIEW

**Comment by akoutmos** [comment]
Thanks for the PR Niko! I rolled out some changes that incorporated this work and will cut a release soon.
